// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpgexqqghswbxiomrads.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ2V4cXFnaHN3Ynhpb21yYWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MzAyNDMsImV4cCI6MjA3ODAwNjI0M30.PK4jXp9viwrgBe8uto26vazeYKZZECu4EACHgnuC7Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});